# 起動時に読み込むプラグイン（autocmd や .vimrc からの関数呼び出しが起動時に必要なもの）

# ペースト
[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'

# File System（g:vimfiler_as_default_explorer が起動時の BufEnter フックに依存）
[[plugins]]
repo = 'Shougo/vimfiler'

# Shell
[[plugins]]
repo = 'Shougo/vimproc'

# 括弧
[[plugins]]
repo = 'luochen1990/rainbow'

# 画面分割の時に使うもの
[[plugins]]
repo = 'kana/vim-submode'
