# 遅延読み込みプラグイン

# Unite
[[plugins]]
repo = 'Shougo/unite.vim'
on_cmd = ['Unite', 'UniteWithCurrentDir', 'UniteWithBufferDir', 'UniteWithProjectDir', 'UniteWithCursorWord', 'UniteWithInput', 'UniteResume']

[[plugins]]
repo = 'Shougo/unite-outline'
on_source = ['unite.vim']

# Shell
[[plugins]]
repo = 'Shougo/vimshell'
on_cmd = ['VimShell', 'VimShellInteractive', 'VimShellPop', 'VimShellTab', 'VimShellCreate', 'VimShellExecute', 'VimShellCurrentDir', 'VimShellBufferDir']

# 括弧
[[plugins]]
repo = 'tpope/vim-surround'
on_map = { n = ['ds', 'cs', 'cS', 'ys', 'yS'], x = ['S', 'gS'], i = ['<C-S>', '<C-G>s', '<C-G>S'] }

# 文字の入れ替え
[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-operator-replace'
depends = ['vim-operator-user']
on_map = { nxo = '<Plug>(operator-replace)' }

# MD 記法
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'tyru/open-browser.vim'
on_cmd = ['OpenBrowser', 'OpenBrowserSearch', 'OpenBrowserSmartSearch']
on_map = { nx = '<Plug>(openbrowser-' }

[[plugins]]
repo = 'previm/previm'
depends = ['open-browser.vim']
on_cmd = ['PrevimOpen']

# QuickRun
[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = ['QuickRun']
on_map = { n = '<Plug>(quickrun' }

# 言語別プラグイン

# TypeScript/JavaScript
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
on_ft = ['typescriptreact']

# Vue
[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']

[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = ['pug']

# Rust
[[plugins]]
repo = 'racer-rust/vim-racer'
on_ft = ['rust']

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']

# Go
[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

# C++
[[plugins]]
repo = 'octol/vim-cpp-enhanced-highlight'
on_ft = ['cpp']

# Dart/Flutter
[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
on_ft = ['dart']

# LaTeX
[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']

# Elm
[[plugins]]
repo = 'lambdatoast/elm.vim'
on_ft = ['elm']

# QML
[[plugins]]
repo = 'peterhoeg/vim-qml'
on_ft = ['qml']

# MQL4
[[plugins]]
repo = 'vobornik/vim-mql4'
on_ft = ['mql4']

# Solidity
[[plugins]]
repo = 'tomlion/vim-solidity'
on_ft = ['solidity']

# PowerShell
[[plugins]]
repo = 'zigford/vim-powershell'
on_ft = ['ps1']

# Terraform
[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = ['terraform']

# TOML
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

# CSV
[[plugins]]
repo = 'mechatroner/rainbow_csv'
on_ft = ['csv']

# PlantUML
[[plugins]]
repo = 'weirongxu/plantuml-previewer.vim'
on_ft = ['plantuml']

# Template engines
[[plugins]]
repo = 'statianzo/vim-jade'
on_ft = ['jade']

[[plugins]]
repo = 'Glench/Vim-Jinja2-Syntax'
on_ft = ['jinja']

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['slim']
