#!/bin/bash
set -eu

#######################################
# User Settings - needs hardcoded
#######################################
USE_WIFI=true
USERNAME='yuki'
SWAP_SIZE='96G'
HOST_NAME='arch-laptop'
ZONE='Asia/Tokyo'
LOCALES=('en_US.UTF-8 UTF-8' 'ja_JP.UTF-8 UTF-8')
VOLUME_GROUP='vg-default'

WIFI_DEV=''
WIFI_SSID=''
WIFI_PASS=''
CPU_BRAND='amd' # amd or intel. for microcode
GPU_DRIVERS='nvidia nvidia-settings nvidia-utils'

DEVICE=''
_BOOT=''
_LVM=''

MIRRORS="$(cat <<'EOM'
# Server list generated by rankmirrors on 2020-10-17
################################################################################
################# Arch Linux mirrorlist generated by Reflector #################
################################################################################
# With:       reflector --protocol https --latest 70 --sort rate --save /etc/pacman.d/mirrorlist
# When:       2020-10-17 03:58:22 UTC
# From:       https://www.archlinux.org/mirrors/status/json/
# Retrieved:  2020-10-17 03:58:11 UTC
# Last Check: 2020-10-17 03:10:29 UTC
Server = https://arch.hu.fo/archlinux/$repo/os/$arch
Server = https://archlinux.mirror.digitalpacific.com.au/$repo/os/$arch
Server = https://mirror.osbeck.com/archlinux/$repo/os/$arch
Server = https://arch.mirror.square-r00t.net/$repo/os/$arch
Server = https://mirror.lty.me/archlinux/$repo/os/$arch
Server = https://mirror.telkomuniversity.ac.id/archlinux/$repo/os/$arch
EOM
)"

#######################################
# Output
#######################################
err() {
  echo -e "\e[31;1m[$(date +'%Y-%m-%dT%H:%M:%S')]\e[m $*" >&2
  exit 1
}
warn() {
  echo -e "\e[31;1m[$(date +'%Y-%m-%dT%H:%M:%S')]\e[m $*" >&2
}
ok() {
  echo -e "\e[32;1m[$(date +'%Y-%m-%dT%H:%M:%S')]\e[m $*" >&2
}
info() {
  echo -e "\e[37;1m[$(date +'%Y-%m-%dT%H:%M:%S')]\e[m $*" >&2
}
breakIfNotSetAny() {
  local vals=(USE_WIFI USERNAME SWAP_SIZE HOST_NAME ZONE LOCALES VOLUME_GROUP WIFI_DEV WIFI_SSID WIFI_PASS CPU_BRAND GPU_DRIVERS DEVICE _BOOT _LVM)
  isOk=true
  for v in ${vals[@]}; do
    [ -z "${!v}" ] && warn "$v must be set" && isOk=false
  done
  [ "$isOk" = "false" ] && err "Set these variable and retry."
}

#######################################
# Functions
#######################################
ntp() {
  timedatectl set-ntp true
}
clean() {
  if [ "$(mount | grep /mnt/boot)" ]; then
    umount /mnt/boot
  fi
  if [ "$(mount | grep /mnt)" ]; then
    umount /mnt
  fi
  if [ "$(lsblk | grep '\[SWAP\]')" ]; then
    swapoff /dev/mapper/$VOLUME_GROUP-swap
  fi
}
conn() {
  if [ "$(pgrep wpa_supplicant)" ]; then return; fi
  if [ -z $WIFI_DEV ]; then
    WIFI_DEV=$(ip link|grep '^[0-9]'|grep -v 'lo:'|grep w|awk '{print $2}'|sed -e's~\(.*\):~\1~')
  fi
  wpa_supplicant -B -i $WIFI_DEV -c <(wpa_passphrase $WIFI_SSID $WIFI_PASS) &>/dev/null
}
partition() {
  # Delete all and create efi, lvm
  echo -e 'o\nY\nn\n\n\n512M\nEF00\nn\n\n\n\n\nw\nY\n'|gdisk $DEVICE
}
encrypt() {
  mkfs.vfat -F32 $DEVICE$_BOOT
  cryptsetup -v luksFormat $DEVICE$_LVM
  cryptsetup luksOpen $DEVICE$_LVM luks
  pvcreate /dev/mapper/luks
  vgcreate $VOLUME_GROUP /dev/mapper/luks
  lvcreate -L $SWAP_SIZE $VOLUME_GROUP -n swap
  lvcreate -l +100%FREE $VOLUME_GROUP -n root
  mkfs.ext4 /dev/mapper/$VOLUME_GROUP-root
  mkswap /dev/mapper/$VOLUME_GROUP-swap
}
mountDevice() {
  mount /dev/mapper/$VOLUME_GROUP-root /mnt
  swapon /dev/mapper/$VOLUME_GROUP-swap
  mkdir /mnt/boot
  mount $DEVICE$_BOOT /mnt/boot
}
applyMirrors() {
  cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.bak
  echo "$MIRRORS" > /etc/pacman.d/mirrorlist
}
installBase() {
  pacstrap /mnt base base-devel linux linux-firmware
  cp /mnt/etc/pacman.d/mirrorlist /mnt/etc/pacman.d/mirrorlist.bak
  echo "$MIRRORS" > /mnt/etc/pacman.d/mirrorlist
  genfstab -pU /mnt >> /mnt/etc/fstab
}
changeRootAndConfigure() {
  arch-chroot /mnt pacman -Syyu
  arch-chroot /mnt ln -sf /usr/share/zoneinfo/$ZONE /etc/localtime
  arch-chroot /mnt hwclock --systohc
  arch-chroot /mnt echo $HOST_NAME > /etc/hostname
  arch-chroot /mnt echo LANG=en_US.UTF-8 > /etc/locale.conf
  for i in $(seq 0 $((${#LOCALES[@]}-1))); do
    arch-chroot /mnt sed -i.org -e "s~^#${LOCALES[$i]}~${LOCALES[$i]}~" /etc/locale.gen
  done
  arch-chroot /mnt locale-gen
}
installPackages() {
  arch-chroot /mnt pacman -S dialog wpa_supplicant git $CPU_BRAND-ucode zsh vim otf-ipafont
  arch-chroot /mnt bash -c 'if [ ! "$(cat /etc/passwd | grep '$USERNAME')" ]; then useradd -m -G wheel -s /bin/zsh '$USERNAME' && passwd '$USERNAME'; fi'
  arch-chroot /mnt sed -i -e 's/^# %wheel ALL=(ALL) ALL/%wheel ALL=(ALL) ALL/' /etc/sudoers
  arch-chroot /mnt sudo -u $USERNAME /bin/bash -c "if !(type yay &>/dev/null); then cd /tmp && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si; fi"
  arch-chroot /mnt yay -Syyu
  # ref) https://wiki.archlinux.org/index.php/Xorg#Installation
  arch-chroot /mnt pacman -S $GPU_DRIVERS xorg-server sddm plasma-desktop networkmanager plasma-nm konsole powerdevil
  arch-chroot /mnt systemctl enable sddm NetworkManager
}
additionals() {
  arch-chroot /mnt chown -R $USERNAME:$USERNAME /home/$USERNAME
  arch-chroot /mnt sudo -u $USERNAME yay -S curl wget rsync dstat \
    google-chrome firefox \
    slack-desktop thunderbird zoom \
    fcitx fcitx-im fcitx-configtool fcitx-mozc \
    bat exa xdotool wmctrl ripgrep pixz pv bluedevil pulseaudio-bluetooth python-pip \
    virtualbox yakuake \
    github-cli \
    google-cloud-sdk \
    nodejs-lts-erbium yarn \
    docker docker-compose \
    qemu libvirt android-studio \
    nginx apache mariadb
  arch-chroot /mnt sudo -u $USERNAME bash -c "if !(type lab &>/dev/null); then yay -S lab; fi"
  # err: java-runtime-common java-environment-common flutter
  # Others
  arch-chroot /mnt systemctl enable bluetooth.service
  arch-chroot /mnt systemctl enable docker.service

  # Link dotfiles
  arch-chroot /mnt sudo -u $USERNAME bash -c "cd /home/$USERNAME && git clone https://github.com/yuki37/dotfiles.git"
  for dotfile in '.zshrc' '.zshrc.zwc' '.Xmodmap' '.xinitrc' '.vimrc' '.sshrc' '.vim' '.gitconfig'; do
    if [ ! -e "/home/$USERNAME/$dotfile" ];then
      arch-chroot /mnt sudo -u $USERNAME ln -snf "/home/$USERNAME/dotfiles/$dotfile" "/home/$USERNAME/$dotfile"
    fi
    if [ ! -e "/root/${dotfile}" ];then
      arch-chroot /mnt ln -snf "/home/$USERNAME/dotfiles/$dotfile" "/root/$dotfile"
    fi
  done

  # Rust
  arch-chroot /mnt bash -c "sudo -u $USERNAME bash -c 'curl https://sh.rustup.rs -sSf|sh -s -- -y' && bash /home/$USERNAME/.cargo/env"
  arch-chroot /mnt bash -c "curl https://sh.rustup.rs -sSf|sh -s -- -y && bash /root/.cargo/env"

  # Android studio
  if [ -f "/mnt/etc/modules" ] && [ ! "$(cat /mnt/etc/modules|grep vhost_net)" ]; then
    echo vhost_net|tee -a /mnt/etc/modules
  fi
  arch-chroot /mnt systemctl enable libvirtd.service

  # Gestures
  arch-chroot /mnt bash -c "cd /tmp && git clone http://github.com/bulletmark/libinput-gestures && cd libinput-gestures && ./libinput-gestures-setup install"
  mkdir -p "/mnt/home/$USERNAME/.config"
  cat <<EOM > "/mnt/home/$USERNAME/.config/libinput-gestures.conf"
gesture swipe right	_internal ws_up
gesture swipe left	_internal ws_down
EOM
  arch-chroot /mnt bash -c "sudo -u $USERNAME libinput-gestures-setup autostart"

  # Mozc fcitx - IME
  local PROFILE="/mnt/home/$USERNAME/dotfiles/.zshrc"
  if [ "$(cat "$PROFILE"|grep '^export XIM_PROGRAM=')" = '' ];then
    echo 'export XIM_PROGRAM=fcitx' >> "$PROFILE"
  fi
  if [ "$(cat "$PROFILE"|grep '^export XIM=')" = '' ];then
    echo 'export XIM=fcitx' >> $PROFILE
  fi
  if [ "$(cat "$PROFILE"|grep '^export GTK_IM_MODULE=')" = '' ];then
    echo 'export GTK_IM_MODULE=fcitx' >> "$PROFILE"
  fi
  if [ "$(cat "$PROFILE"|grep '^export QT_IM_MODULE=')" = '' ];then
    echo 'export QT_IM_MODULE=fcitx' >> "$PROFILE"
  fi
  if [ "$(cat "$PROFILE"|grep '^export XMODIFIERS=')" = '' ];then
    echo 'export XMODIFIERS="@im=fcitx"' >> "$PROFILE"
  fi

  if [ "$(cat "$PROFILE"|grep '')"  = 'type fcitx-autostart &>/dev/null && (fcitx-autostart&>/dev/null &)' ];then
    echo 'type fcitx-autostart &>/dev/null && (fcitx-autostart&>/dev/null &)' >> "$PROFILE"
  fi

  # Virtualbox
  arch-chroot /mnt usermod -aG vboxusers $USERNAME
  # wget https://download.virtualbox.org/virtualbox/6.1.6/Oracle_VM_VirtualBox_Extension_Pack-6.1.6.vbox-extpack
  # virtualbox Oracle_VM_VirtualBox_Extension_Pack-6.1.6.vbox-extpack
  # rm Oracle_VM_VirtualBox_Extension_Pack

  # vim-dein
  arch-chroot /mnt sudo -u $USERNAME pip install --user pynvim
  arch-chroot /mnt pip install pynvim
  local DEIN_INSTALLER='https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh'

  if [ -d "/mnt/home/$USERNAME/.cache/dein" ];then
    rm -rf "/mnt/home/$USERNAME/.cache/dein"
  fi
  arch-chroot /mnt sh -c "$(curl -fsSL "$DEIN_INSTALLER")" -- "/home/$USERNAME/.cache/dein"
  if [ -d "/mnt/root/.cache/dein" ];then
    rm -rf /mnt/root/.cache/dein
  fi
  arch-chroot /mnt sh -c "$(curl -fsSL "$DEIN_INSTALLER")" -- /root/.cache/dein

  # Yakuake
  if [ ! -f /mnt/home/$USERNAME/.config/systemd/user/yakuake.service ]; then
    mkdir -p "/mnt/home/$USERNAME/.config/systemd/user"
    cat <<EOM > "/mnt/home/$USERNAME/.config/systemd/user/yakuake.service"
[Unit]
Description=yakuake daemon

[Service]
ExecStart=/usr/bin/yakuake
Restart=always

[Install]
WantedBy=default.target
EOM
    arch-chroot /mnt chown -R $USERNAME:$USERNAME /home/$USERNAME
    # arch-chroot /mnt systemctl --user enable yakuake
  fi

}
finalize() {
  arch-chroot /mnt bootctl --path=/boot install
  local entry="$(cat <<EOM > /mnt/boot/loader/entries/arch.conf
title Arch Linux
linux /vmlinuz-linux
initrd /$CPU_BRAND-ucode.img
initrd /initramfs-linux.img
options cryptdevice=UUID=$(blkid $DEVICE$_LVM|sed -e's/.* UUID="\(.*\)" TYPE.*/\1/'):lvm:allow-discards resume=/dev/mapper/$VOLUME_GROUP-swap root=/dev/mapper/$VOLUME_GROUP-root rw quiet
EOM
)"
  local entry="$(cat <<EOM > /mnt/boot/loader/loader.conf
timeout 0
default arch
editor 0
EOM
)"
  sed -i -e's/MODULES=(.*)/MODULES=(ext4)/' /mnt/etc/mkinitcpio.conf
  sed -i -e's/HOOKS=(.*)/HOOKS=(base udev autodetect modconf block keymap encrypt lvm2 resume filesystems keyboard fsck)/' /mnt/etc/mkinitcpio.conf
  arch-chroot /mnt mkinitcpio -p linux
  umount /mnt/boot
  umount /mnt
}

#######################################
# Main process
#######################################
main() {
  breakIfNotSetAny
  info 'Setting ntp' && ntp && ok "DONE" || err "FAILED"
  info 'Connecting to the internet' && conn && ok "DONE" || err "FAILED"
  info 'Cleaning mount points' && clean && ok "DONE" || err "FAILED"
  info 'Partitioning devices' && partition && ok "DONE" || err "FAILED"
  info 'Encrypting device' && encrypt && ok "DONE" || err "FAILED"
  info 'Mounting device' && mountDevice && ok "DONE" || err "FAILED"
  info 'Applying mirrors' && applyMirrors && ok "DONE" || err "FAILED"
  info 'Installing base systems' && installBase && ok "DONE" || err "FAILED"
  info 'Chaging into root' && changeRootAndConfigure && ok "DONE" || err "FAILED"
  info 'Installing packages' && installPackages && ok "DONE" || err "FAILED"
  info 'Additional packages' && additionals && ok "DONE" || err "FAILED"
  info 'Finalizing' && finalize && ok "DONE" || err "FAILED"
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  if [ $# -eq 0 ]; then
    main "$@"
  else
    $1
  fi
fi


