#!/bin/bash

set -eu

TARGET="$HOME/di/ext"

if [ ! -d "$TARGET/lost+found" ]; then
  uuids=()
  while read -r uuid _ _; do
    if ! [[ $uuid =~ ^\{?[A-F0-9a-f]{8}-[A-F0-9a-f]{4}-[A-F0-9a-f]{4}-[A-F0-9a-f]{4}-[A-F0-9a-f]{12}\}?$ ]]; then
      continue
    fi
    if ! sudo file -sL "/dev/disk/by-uuid/$uuid" | grep -q LUKS; then
      continue
    fi
    uuids+=("$uuid")
  done< <(sudo lsblk -o UUID,NAME,TYPE | grep disk | grep -v nvme)

  read -rsp "Enter passphrase: " passwd; echo

  for uuid in "${uuids[@]}"; do
    id=$(echo "$uuid" | awk -F'-' '{print $1}')
    echo -n "[uuid] $uuid .."

    if lsblk | grep "lv-$id"; then
      echo Already mounted
      continue
    fi
    if echo "$passwd" | sudo cryptsetup luksOpen "/dev/disk/by-uuid/$uuid" "lv-$id"; then
      echo OK
    else
      echo NG
    fi
  done

  sleep 1
  sudo mount /dev/mapper/vg--ext-lv--ext "$TARGET"
fi

exit

if ! lsblk | grep -q '/var/lib/docker'; then
  sudo mount --bind "$TARGET/Cached/docker" /var/lib/docker
fi

if ! lsblk | grep -q "$HOME/.cache/yay"; then
  sudo mount --bind "$TARGET/Cached/.cache/yay" "$HOME/.cache/yay"
fi

echo 'moving Trash..'
rsync -avP "$HOME/.local/share/Trash/" "$TARGET/Cached/Trash/"

echo 'done'
