#!/bin/bash
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CODEX_HOME="${CODEX_HOME:-$HOME/.codex}"
MARK="# generated by dotfiles/agents/build.sh"

# Claude Code reads hooks only from settings.json, so the shared hooks.json is merged in.
settings="$DIR/llms/claude/settings.json"
jq --indent 2 --slurpfile h "$DIR/hooks/hooks.json" '.hooks = $h[0].hooks' "$settings" > "$settings.tmp"
mv "$settings.tmp" "$settings"

# Codex has no rules directory; all rules are concatenated into one AGENTS.md.
{
  for f in "$DIR"/rules/*.md; do
    cat "$f"
    echo
  done
  cat "$DIR/llms/codex/AGENTS.md"
} > "$CODEX_HOME/AGENTS.md"

# Codex agents are TOML; the Markdown definitions in agents/ are the source.
mkdir -p "$CODEX_HOME/agents"
shopt -s nullglob
for f in "$CODEX_HOME"/agents/*.toml; do
  grep -qFx "$MARK" "$f" && rm -- "$f"
done
for f in "$DIR"/agents/*.md; do
  name="$(sed -n 's/^name: *//p' "$f" | head -1 | tr '-' '_')"
  description="$(sed -n 's/^description: *//p' "$f" | head -1)"
  tools="$(sed -n 's/^tools: *//p' "$f" | head -1)"
  body="$(awk 'f>=2{print} /^---$/{f++}' "$f" | sed '/./,$!d')"
  if grep -q "'''" <<<"$body"; then
    echo "error: $f contains ''' which cannot be embedded in a TOML literal string" >&2
    exit 1
  fi
  {
    echo "$MARK"
    echo "name = \"$name\""
    echo "description = \"${description//\"/\\\"}\""
    # An agent without file-writing tools in Claude Code maps to a read-only sandbox.
    if [[ -n "$tools" ]] && ! grep -qE '\b(Edit|Write|MultiEdit|NotebookEdit)\b' <<<"$tools"; then
      echo 'sandbox_mode = "read-only"'
    fi
    echo "developer_instructions = '''"
    echo "$body"
    echo "'''"
  } > "$CODEX_HOME/agents/$name.toml"
done

# Codex controls implicit invocation through agents/openai.yaml instead of frontmatter.
for f in "$DIR"/skills/*/SKILL.md; do
  skill_dir="$(dirname "$f")"
  if grep -qx 'disable-model-invocation: *true' "$f"; then
    mkdir -p "$skill_dir/agents"
    printf 'policy:\n  allow_implicit_invocation: false\n' > "$skill_dir/agents/openai.yaml"
  else
    rm -f "$skill_dir/agents/openai.yaml"
    rmdir "$skill_dir/agents" 2>/dev/null || true
  fi
done
